### ISSUE TITLE
Error: Cannot find module 'bunyan'

### ISSUE THREAD

**Issue by slia-stryber** [oracle/oci-typescript-sdk#267] opened 2024-02-15 17:34 UTC
```
npm install oci-objectstorage
```

import the module somewhere
```
import { ObjectStorageClient } from 'oci-objectstorage';
```

run the application
```
Error: Cannot find module 'bunyan'
Require stack:
- ***/node_modules/oci-common/lib/log.js
- ***/node_modules/oci-common/lib/retrier.js
- ***/node_modules/oci-common/lib/circuit-breaker.js
- ***/node_modules/oci-common/lib/utils.js
- ***/node_modules/oci-common/lib/headers.js
- ***/node_modules/oci-common/lib/helper.js
- ***/node_modules/oci-common/lib/signer.js
- ***/node_modules/oci-common/index.js
- ***/node_modules/oci-objectstorage/lib/client.js
- ***/node_modules/oci-objectstorage/index.js
...
```

**Comment by jyotisaini** [comment] 2024-02-15 17:38
@slia-stryber Can you try running `npm install bunyan` ? That should solve the issue for now. However we will take a look internally as why bunyan logger is being used in the objectstorage client.

**Comment by slia-stryber** [comment] 2024-02-15 17:42
> @slia-stryber Can you try running `npm install bunyan` ? That should solve the issue for now. However we will take a look internally as why bunyan logger is being used in the objectstorage client.

Yes, definitely, but I belive that 
```
"bunyan": "^1.8.15",
```
should be somewhere in the **package.json**

**Comment by jyotisaini** [comment] 2024-02-15 17:48
Yes thats correct. But we do not use Bunyan logger in the clients. if its is giving an error for missing module bunyan, the issue is not that module is missing from package.json but it should not have been used in the client in the first place. We will look in to it as why it's complaining for bunyan.

**Comment by slia-stryber** [comment] 2024-02-15 18:00
> Yes thats correct. But we do not use Bunyan logger in the clients. if its is giving an error for missing module bunyan, the issue is not that module is missing from package.json but it should not have been used in the client in the first place. We will look in to it as why it's complaining for bunyan.

[https://github.com/oracle/oci-typescript-sdk/blob/e0cff556fe6cb1ab3ff790de61fce433c4deef36/lib/common/lib/log.ts#L10](https://github.com/oracle/oci-typescript-sdk/blob/e0cff556fe6cb1ab3ff790de61fce433c4deef36/lib/common/lib/log.ts#L10)

**Comment by vpeltola** [comment] 2024-02-20 13:31
This problem comes with version 2.79.1.  As a workaround, I downgraded to 2.79.0, and the problem went away.

**Comment by jyotisaini** [comment] 2024-02-22 19:03
Hi @vpeltola This issue has been fixed in the latest release. Can you please upgrade the sdk version ot the latest and confirm it works for you?

**Comment by NiviPari** [comment] 2024-03-28 04:44
Closing this issue as it is fixed with latest release . @vpeltola  please feel free to reopen if incase you are still seeing this issue. Thanks !

**Closed by NiviPari** 2024-03-28 04:44 UTC
Labels: SDK
