### ISSUE TITLE
Socket hangup when uploading multiple files.

### ISSUE THREAD

**Issue by rafaferry** [oracle/oci-typescript-sdk#65] opened 2021-04-16 21:20 UTC
Hello,

I am developing a application that scans a folder, and uploads any file to oracle-object-storage. The uploads run in parallel, and 
very often i Run into this error:

 OciError: request to [...] failed, reason: socket hang up
ora-object-storage-uploader_1  |     at GenericRetrier.<anonymous> (/app/node_modules/oci-common/lib/retrier.js:83:38)
ora-object-storage-uploader_1  |     at Generator.throw (<anonymous>)
ora-object-storage-uploader_1  |     at rejected (/app/node_modules/oci-common/lib/retrier.js:10:65)
ora-object-storage-uploader_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
ora-object-storage-uploader_1  |   statusCode: 'ECONNRESET',
ora-object-storage-uploader_1  |   serviceCode: 'unknown code',
ora-object-storage-uploader_1  |   opcRequestId: 'unknown'

Here is my code:
```const chokidar = require('chokidar');
const common = require('oci-common');

const { ObjectStorageClient } = require('oci-objectstorage');
const { UploadManager } = require('oci-objectstorage');

const fs = require('fs');
const pathToWatch = '/x';
const watcher = chokidar.watch(pathToWatch, {
  persistent: true,
  ignoreInitial: false,
  followSymlinks: true,
  depth: 99,
  awaitWriteFinish: {
    pollInterval: 5000,
    stabilityThreshold: 10000,
  },
});

watcher.on('add', (path) => {
  console.log('new File found', path);
  upload(path, 1);
});

const provider = new common.ConfigFileAuthenticationDetailsProvider('./.ora-config');
const oraClient = new ObjectStorageClient({ authenticationDetailsProvider: provider });

function upload(path, tryCount) {
  const uploadManager = new UploadManager(oraClient, { enforceMD5: true });

  const loggerCallback = (res) => {
    console.log('Progress: ', res);
  };

  uploadManager
    .upload(
      {
        content: { filePath: path },
        requestDetails: {
          namespaceName: 'x',
          bucketName: 'x',
          objectName: path,
        },
      },
      loggerCallback,
    )
    .then(() => {
      console.log('SUCESS', path);
      fs.unlink(path, (err) => {
        if (err) {
          console.log('error removing file', path);
        } else {
          console.log('file removed:', path);
        }
      });
    })
    .catch((err) => {
      console.log('error uploading', err, path);
      console.log(`retrying  ${path}. Tentativa ${++tryCount}`);
      upload(path, tryCount);
    });
}
```

Am I doing something wrong, or there is something wrong with the api? Some files only succeed after five attempts. 
Also note that this code uploads the files concurrently, sometimes running with 8 100mb files concurrently.

Ah, this code runs on oracle cloud region sa-saopaulo-1 on a E4.flex with 4 OCPU's and 4G RAM.

Thanks in advance.

**Comment by waruwaruwaru** [comment] 2021-04-20 21:29
Hi @rafaferry, thanks for reporting this issue. I have to look into this issue but in the meantime, can you try passing in a partSize of 10MB when creating the upload manager? i.e:
`
const partSize = 10 * 1024 * 1024;  //10MB part size
const uploadManager = new UploadManager(oraClient, { enforceMD5: true, partSize: partSize });
`
By default the upload manager will use a partSize of 20MB but I think decreasing it to 10MB might help with your issue. Let me know if the socket timeout still occurs.

**Comment by rafaferry** [comment] 2021-04-20 22:43
Thank you, I will try this.

As soon as I get it done will update here with the results.

**Comment by rafaferry** [comment] 2021-04-26 22:15
Hello,

I tried changing the part size to 10MB, and even 5MB but the problem still occurs.

Here is the log:

```
OciError: request to [...]?uploadId=c72e18a3-6f29-e5dc-9296-3ae2661b0a72&uploadPartNum=9 failed, reason: socket hang up
    at GenericRetrier.<anonymous> (/app/node_modules/oci-common/lib/retrier.js:83:38)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/oci-common/lib/retrier.js:10:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  statusCode: 'ECONNRESET',
  serviceCode: 'unknown code',
  opcRequestId: 'unknown'
  ```
  
  Retrying the upload eventually makes it work.

**Comment by waruwaruwaru** [comment] 2021-04-27 17:06
Thanks @rafaferry, I will look into this.

**Comment by rafaferry** [comment] 2021-04-30 16:20
Hello,

I was looking into my logs, and found another kind of error. Here is the stacktrace:
```
 [ERR_OUT_OF_RANGE]: The value of "end" is out of range. It must be >= 0 && <= 9007199254740991. Received -1
    at new ReadStream (internal/fs/streams.js:107:5)
    at Object.createReadStream (fs.js:1919:10)
    at NodeFSBlob.<anonymous> (/app/node_modules/oci-objectstorage/lib/upload-manager/node-fs-blob.js:41:25)
    at Generator.next (<anonymous>)
    at /app/node_modules/oci-objectstorage/lib/upload-manager/node-fs-blob.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/oci-objectstorage/lib/upload-manager/node-fs-blob.js:8:12)
    at NodeFSBlob.getData (/app/node_modules/oci-objectstorage/lib/upload-manager/node-fs-blob.js:40:16)
    at UploadManager.<anonymous> (/app/node_modules/oci-objectstorage/lib/upload-manager/upload-manager.js:71:46)
    at Generator.next (<anonymous>) {
  code: 'ERR_OUT_OF_RANGE'
```

Don't know if its is related, but since it's in the same code, im posting here.

At first I thought it was some problem in my code, and that I was trying to upload an inexistent file. But I added this check before upload:

`if (!fs.existsSync(path)) return`

And the error stills occurs. Retrying the upload eventually makes it work.

I'm Sorry that I can't provide clear steps for reproducing this. It does not occurs every time, and I'm afraid that it has something to do with using multiple instances of UploadManager concurrently, but I can't know for sure.

**Comment by waruwaruwaru** [comment] 2021-05-04 18:13
Hey @rafaferry thanks for reporting this. I can reproduce the socket hang up error but I cannot reproduce the out of range error. This error you showed me is most likely due to giving a **end** that is greater than the maximum safe integer. Though I am currently not sure how this issue occurs. The **end** parameter is most likely coming from creating a stream because when creating the stream, we specify the start/end. I will let you know when I send out an update that should fix the socket timeout issue, with that fix lets see if these errors still occur again.

**Comment by rafaferry** [comment] 2021-05-14 13:07
Hey @waruwaruwaru, I think I now how to reproduce the [ERR_OUT_OF_RANGE]. 

This is happening to files without content. I know, I can check if the file has any content written before triggering the upload, but there may be some cases where I do want the file to be uploaded, even if it is empty.

I've tryed to attach an example of file here but github doesn't allow upload of empty files.

**Comment by waruwaruwaru** [comment] 2021-05-17 16:42
@rafaferry I currently have a PR out internally for review. Once that gets released to public, I will notify you. It should fix the problems. Thank you for reporting these issues :)

**Comment by waruwaruwaru** [comment] 2021-06-01 18:22
@rafaferry, can you try the latest version of the SDK (v1.20.1) and see if you still get into this issue? Thank you.

**Comment by waruwaruwaru** [comment] 2021-06-08 18:11
@rafaferry I will be closing this issue but please feel free to reopen this if you run into the issues again with the latest SDK. Thank you for reporting this.

**Comment by rafaferry** [comment] 2021-06-09 14:49
Hey @waruwaruwaru,

I'm sorry for the delay. 
I've just tested with the sdk 1.20.2, and it still has some problem, but it may be network / infrastructure related.

Some of my uploads are failing with this error:
```
OciError: request to https://objectstorage.sa-saopaulo-1.oraclecloud.com/n/grjlblbhbzvv/b/webrtc-recordings/u/reuniaosebraemg2.connsult.com.br%2F4609c330-7a9b-45b8-8c82-9f5b837becf4%2Fvideoroom-1885325096542042-user-1607895054367132-1623239962297725-video.mjr?uploadId=8ad43ff6-98cf-e570-c6a8-269a3d8f8405&uploadPartNum=14 failed, reason: Client network socket disconnected before secure TLS connection was established
    at GenericRetrier.<anonymous> (/app/node_modules/oci-common/lib/retrier.js:87:38)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/oci-common/lib/retrier.js:10:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  statusCode: 'ECONNRESET',
  serviceCode: 'unknown code',
  opcRequestId: 'unknown'
}
```
I dont know if this is relevant, but this code runs on oracle kubernetes engine, cloud region sa-saopaulo-1.

**Comment by waruwaruwaru** [comment] 2021-06-09 17:24
Hey @rafaferry, thank you for getting back. I was wondering if there is any change in the environment recently. This error: `Client network socket disconnected before secure TLS connection was established` suggests proxy error from my research. Did you get this error in the past? I know you were getting a socket hangup before but this error looks new. But if its a proxy error, I am not sure why some files can be uploaded but some files fail.

Another question I have is, do the same files always reproduce the same error? Or is it different files at random times? If it is the same files that reproduces the error, can you tell me some characteristics about the files that is causing this error? Like the size, the file format, etc. Any detail will help me debug this. I am not able to reproduce this on my end at the moment.

**Comment by waruwaruwaru** [comment] 2021-06-14 23:34
Hi @rafaferry, is there an update on this? Any information you can provide me from my previous post? Thanks.

**Comment by rafaferry** [comment] 2021-06-15 15:41
Hey @waruwaruwaru I'm sorry to keep you waiting.

I dont think it's a proxy error. Nothing in my environment has changed except the OCI sdk version. 

The problem seem's the same with the socket hangup. Random files, at random times, and retrying the upload works.

To me it looks like oracle kubernetes engine (or something specifc to my environment) has some sporadic network failure, that is causing these errors in the oci-sdk.

Maybe the sdk should handle network errors and retry for itself, without throwing uncaught exceptions.

Anyway, this is not causing me any trouble, because My code already retry uploads until it succeeds.

**Comment by waruwaruwaru** [comment] 2021-06-15 17:11
Hey @rafaferry thanks for getting back. The SDK does internally do retry on network error as well. The OciError that the SDK returned was the error that we received when making the HTTP call. Does this issue happen in your local environment? If you ran the same code locally while trying to upload the same files, does this issue still occur?

**Comment by rafaferry** [comment] 2021-06-15 18:03
I've just ran this code locally for arround 30 min, uploading the files in a loop. The problem did not occur. 

Must be something with my env.

I think you can close this issue.

Thank you.

**Comment by waruwaruwaru** [comment] 2021-06-22 18:43
Thanks for getting back @rafaferry. The latest SDK (v1.21.1) will now show logs before doing a retry. If you are not able to see the retries being done at the SDK level, feel free to reach out and let me know.

**Comment by waruwaruwaru** [comment] 2021-06-25 19:16
I will be closing this issue. If there are any issues you suspect from the SDK or if you are not able to see any logs on the retry done by the SDK, please feel free to re-open this issue again. Thanks again for reporting this issue @rafaferry.

**Closed by waruwaruwaru** 2021-06-25 19:16 UTC
Labels: SDK
