### ISSUE TITLE
Alloy config file not found at [object Object], enabling all OCI services as default.

### ISSUE THREAD

**Issue by sunao417t33** [oracle/oci-typescript-sdk#243] opened 2023-11-08 10:01 UTC
Thank you for developing the OCI SDK! 
My app, which uses the oci-typescript-sdk, is currently displaying the following message:

 "Alloy config file not found at [object Object], enabling all OCI services as default."

- Node.js v16.20.2
- TypeScript 4.1.3
- oci-typescript 2.73.1

This message is generated from the `alloyConfiguration.ts` file added in version 2.73.1, and it appears to be triggered by the absence of the `alloy-config.json` file. I think this message should not be shown to users who do not use OCI Alloy. 

I would prefer that `AlloyConfiguration.alloyConfiguration()` is executed only if `isAlloyRegion` is true.

oci-typescript-sdk/lib/common/lib/region.ts:
```typescript

private constructor(regionId: string, realm: Realm, regionCode?: string, isAlloyRegion: boolean = false) {
    this._realm = realm;
    this._regionId = regionId;
    if (regionCode) this._regionCode = regionCode;
    AlloyConfiguration.alloyConfiguration();
    if (isAlloyRegion) {
        Region.ALLOY_REGIONS.set(regionId, this);
    } else {
        Region.KNOWN_REGIONS.set(regionId, this);
    }
}

```
Is this the intended behavior?

**Comment by jyotisaini** [comment] 2023-11-08 20:02
Thanks for reporting this @sunao417t33 . No this is not the intended behaviour. Can you let us know what is the log.level you are using in your app?

**Comment by sunao417t33** [comment] 2023-11-09 00:18
@jyotisaini 
Thank you for your response. 
I haven't configured a specific logging level in my app; I simply let it run in Node.js. 
I apologize if I misunderstood your question.

My app is a command-line tool that I created by extending the original oci-typescript-sdk/examples/typescript/audit.ts. Consequently, I can reproduce this issue using the following commands:

```bash
$ mkdir test && cd test
$ npm install typescript@4.1.3
$ npm install oci-sdk
$ cp ../oci-typescript-sdk-master/examples/typescript/audit.ts .
$ node_modules/typescript/bin/tsc audit.ts
$ node audit.js
Alloy config file not found at [object Object], enabling all OCI services as default
Alloy config file not found at [object Object], enabling all OCI services as default
Alloy config file not found at [object Object], enabling all OCI services as default
Alloy config file not found at [object Object], enabling all OCI services as default

```

If it appears that I am using the above SDK incorrectly, I'd appreciate knowing!

**Comment by zotijs** [comment] 2023-11-13 13:09
+1

**Comment by alexchristopoulos** [comment] 2023-11-13 13:15
+1

**Comment by jyotisaini** [comment] 2023-11-16 00:04
Thanks @sunao417t33 . Our team is working on a fix to remove these messages and executed  only when isAlloyRegion is True

**Comment by petr-synek** [comment] 2023-11-17 14:09
This would not be an issue if you fix #128 . Here again you use console.log() to output debugging information, which is totally unacceptable for a library.

**Comment by JoshuaWR** [comment] 2023-12-12 21:50
Hi @sunao417t33, this issue should be resolved with changes made in the newest release of the SDK, [v2.76.0](https://github.com/oracle/oci-typescript-sdk). Could you try upgrading to this version?

**Comment by sunao417t33** [comment] 2023-12-13 08:55
Thanks @JoshuaWR. I upgraded to 2.76.0 and it works!  Please close.

**Closed** 2023-12-13 16:39 UTC
Labels: SDK
